[placeholders.chip]
type = "string"
prompt = "What microcontroller name?"
#choices = ["", ""]
default = "stm32f411ceu6"

[placeholders.version]
type = "string"
prompt = "What HAL version to use?"
choices = ["last-release", "git"]
default = "last-release"

[placeholders.rtic]
type = "bool"
prompt = "Is it RTIC-based application?"
default = false

[placeholders.defmt_enabled]
type = "bool"
prompt = "Will this program use defmt logger?"
default = false

[placeholders.svd]
type = "bool"
prompt = "Do you want to load SVD and add it to VSCode task?"
default = false

[hooks]
#init = [...]
pre = ["pre-script.rhai"]
#post = [...]