[placeholders.chip]
type = "string"
prompt = "What microcontroller name?"
#choices = ["", ""]
default = "stm32f411ceu6"

[placeholders.rtic]
type = "bool"
prompt = "Is it RTIC-based application?"
default = false

[placeholders.svd]
type = "bool"
prompt = "Do you want to load SVD and add it to VSCode task?"
default = false

[hooks]
#init = [...]
pre = ["pre-script.rhai"]
#post = [...]
